//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public string NewsName { get; set; }
        public string NewsDesciption { get; set; }
        public int CategoryNewsID { get; set; }
        public int AuthorID { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Delete { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual CategoryNew CategoryNew { get; set; }
    }
}
